<h1>Loaded modules</h1>

<table class="table table-condensed">
    <tr>
        <th>Module</th>
        <th>HEAD</th>
        <th>upstream/master</th>
        <th>Status</th>
    </tr>
    <?php foreach ($this->modules as $name => $data) : ?>
    <tr>
        <td><?php echo $name ?></td>
        <td><?php echo $data['local'] ?></td>
        <td><?php echo $data['upstreamHash'] ?></td>
        <td><?php echo $data['status']; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
