<?php $this->headScript()->appendFile('/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet('/css/at-datagrid/datagrid.css') ?>

<? if ($this->customJs): ?>
    <?php foreach ($this->customJs as $file): ?>
        <?php $this->headScript()->appendFile($file) ?>
    <?php endforeach; ?>
<? endif; ?>

<div class="page-header clearfix">
    <h1><?php echo $this->translate($this->title) ?></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <?php if (count($form->getFieldSets()) > 0): ?>
            <?php echo $this->render('at-datagrid/form/form-tabbed.phtml'); ?>
        <?php else: ?>
            <?php echo $this->render('at-datagrid/form/form-plain.phtml'); ?>
        <?php endif; ?>
    </div>
</div>