<?php $this->headScript()->appendFile('/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet('/css/at-datagrid/datagrid.css') ?>

<div class="page-header clearfix">
    <h1><?php echo $this->translate('Edit') ?></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <a class="pull-right" href="<?= $this->backUrl ?>">
            &leftarrow; <?= $this->translate('Back'); ?>
        </a>
        <?php echo $this->render('at-admin/form.phtml'); ?>
    </div>
</div>