<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(null, array(), array(), true));
    $form->setAttribute('method', 'post');
    $form->setAttribute('id', 'at-datagrid-form');
    $form->setAttribute('role', 'form');
    $form->setAttribute('class', 'form-horizontal');

    echo $this->form()->openTag($form);
?>

<div>
    <?= $this->render('at-admin/_elements.phtml', array('elements' => $form->getElements())) ?>
</div>

<?php foreach ($formSections as $section): ?>

    <h4><?= $this->translate($section['label']); ?></h4>

    <div>
        <?= $this->render('at-admin/_elements.phtml', array('elements' => $section['elements'])) ?>
    </div>
<?php endforeach; ?>

<div class="form-group">
    <div class="col-md-offset-3 col-md-7">
        <?php
            $submit = $form->get('submit');
            $submit->setAttributes(array('class' => 'btn btn-info pull-left'));
        ?>
        <?php echo $this->formSubmit($submit) ?>
        <a class="pull-right" href="<?php echo $this->backUrl ?>">
            <?php echo $this->translate('Back to list'); ?>
        </a>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>