<?php
    /** @var \Zend\Form\Form $form */
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(null, [], [], true));
    $form->setAttribute('method', 'post');
    $form->setAttribute('id', 'at-datagrid-form');
    $form->setAttribute('role', 'form');
    $form->setAttribute('class', 'form-horizontal');

    echo $this->form()->openTag($form);
?>

<div id="section-general">
    <?= $this->render('at-admin/_elements.phtml', ['elements' => $form->getElements()]) ?>
</div>

<?php foreach ($form->getFieldSets() as $fieldset): ?>
    <div id="section-<?= $fieldset->getName() ?>">
        <h4><?= $this->translate($fieldset->getLabel()); ?></h4>
        <?= $this->render('at-admin/_elements.phtml', ['elements' => $fieldset->getElements()]) ?>
    </div>
<?php endforeach; ?>

<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
        <?php
            $submit = $form->get('submit');
            $submit->setAttributes(['class' => 'btn btn-info pull-left']);
        ?>
        <?= $this->formSubmit($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>