<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/admin.css')
                             //->prependStylesheet('//netdna.bootstrapcdn.com/bootswatch/2.1.1/spacelab/bootstrap.min.css')
                             ->prependStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css') ?>

        <!-- Scripts -->
        <?= $this->headScript()->prependFile('//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js')
                               ->prependFile('//code.jquery.com/jquery.min.js')
                               ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))?>

    </head>

    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?= $this->url('zfcadmin') ?>"></a>
                    <div class="nav-collapse">
                        <?= $this->navigation('admin_navigation')
                                 ->menu()
                                 ->setUlClass('nav')
                                 ->setMaxDepth(0)
                                 ->setRenderInvisible(false)?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <?= $this->content; ?>

            <hr>

            <footer>
                 <p>&copy; 2012 - 2013 Knibble.Ru. All rights reserved.</p>
            </footer>

        </div> <!-- /container -->

        <?= $this->inlineScript() ?>
    </body>
</html>
