<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('AtAdmin Admin Panel')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- Styles -->
        <?php echo $this->headLink()
            ->appendStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/css/at-admin/admin.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile('//code.jquery.com/jquery.min.js')
            ->appendFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js') ?>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">AtAdmin</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav main-menu">
                        <?php foreach ($this->navigation('admin-navigation')->getContainer() as $item): ?>
                            <?php if ($item->hasPages()): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Profile">
                                        <?php echo $this->translate($item->getLabel()) ?>
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($item->getPages() as $page): ?>
                                            <li><a href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a></li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                            <?php else: ?>
                                <li><a href="<?php echo $item->getHref() ?>"><?php echo $this->translate($item->getLabel()) ?></a></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>

                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="<?= $this->translate('Profile') ?>">
                                <span class="glyphicon glyphicon-user"></span>
                                Username<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="" title="<?= $this->translate('Profile') ?>">
                                        <span class="b"><?= $this->translate('Profile') ?></span>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="" title="<?= $this->translate('Logout') ?>"><?= $this->translate('Logout') ?></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>

            <footer class="clearfix">
                 <p>Powered by <a href="https://github.com/atukai/AtAdmin" target="_blank">AtAdmin</a></p>
            </footer>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>