<? $this->headScript()->appendFile('/js/at-admin/datagrid.js') ?>
<? $this->headLink()->appendStylesheet('/css/at-admin/datagrid.css') ?>

<div class="row item-info">
    <div class="span2 back">
        <a href="" title="<?= $this->translate('Back to list'); ?>">
            <i class="icon-arrow-left"></i> <?= $this->translate('Back to list'); ?>
        </a>
    </div>
    <div class="info">
    </div>
</div>

<div class="row">
    <?= $this->render('at-admin/datagrid/form') ?>
</div>