<?

$form = $this->grid->getForm();
$form->prepare();
$form->setAttribute('action', $this->url(null, array('action' => 'create')));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'datagrid-form');
$form->setAttribute('class', 'form-horizontal grid-form');

echo $this->form()->openTag($form);
?>
    <? foreach ($form->getElements() as $element): ?>
        <div class="control-group">
            <? if ($element->getAttribute('type') == 'hidden'): ?>
                <?= $this->formHidden($element) ?>
            <? else: ?>
                <? $element->setLabelAttributes(array('class' => 'control-label')); ?>
                <?= $this->formLabel($element) ?>
                <div class="controls">
                    <?= $this->formElement($element) ?>
                    <p class="help-block">
                        <?= $this->formElementErrors($element); ?>
                    </p>
                </div>
            <? endif; ?>
        </div>
    <? endforeach; ?>

    <div class="form-actions">
        <button type="submit" class="btn btn-info">Create</button>
    </div>

<?= $this->form()->closeTag(); ?>